- name: Run all required playbooks in sequence to run pipeline
  hosts: localhost
  gather_facts: no
  tasks: []

- import_playbook: p1_configure_basic_tools.yml
- import_playbook: p2_assign_hostnames.yml
- import_playbook: p3_customise.yml
- import_playbook: p4_configure_mgmt_nodes.yml
- import_playbook: p5_common_keys.yml
- import_playbook: p6_share_keys.yml
- import_playbook: p7_userfile.yml
- import_playbook: p8_hadoop_firewall.yml
- import_playbook: p9_install_hadoop.yml
- import_playbook: p10_config_mgmt.yml
- import_playbook: p11_config_worker.yml
- import_playbook: p12_start_hadoop.yml
- import_playbook: p13_install_spark.yml
- import_playbook: p14_spark_path.yml
- import_playbook: p15_firewall_spark.yml
- import_playbook: p16_start_spark_master.yml
- import_playbook: p17_start_spark_worker.yml
- import_playbook: p18_install_dep.yml
- import_playbook: p19_prometheus.yml
- import_playbook: p20_node_exporter.yml
- import_playbook: p21_config_prometheus.yml
- import_playbook: p22_spark_metrics.yml
- import_playbook: p23_grafana.yml
- import_playbook: p24_config_ports.yml
- import_playbook: p25_custom_dashboard.yml
- import_playbook: p26_remove_unwanted.yml
- import_playbook: p27_setup_env.yml
- import_playbook: p28_install_rbmq.yml
- import_playbook: p29_start_app.yml
- import_playbook: p30_dataset.yml
- import_playbook: p31_install_airflow.yml
- import_playbook: p32_start_airflow.yml
