- name: Run all required playbooks in sequence to run pipeline
  hosts: localhost
  gather_facts: no
  tasks: []

- import_playbook: p3_customise.yml
- import_playbook: p4_configure_mgmt_nodes.yml
- import_playbook: p5_common_keys.yml
- import_playbook: p6_share_keys.yml
- import_playbook: p7_userfile.yml
- import_playbook: p8_hadoop_firewall.yml
- import_playbook: p9_install_hadoop.yml
- import_playbook: p10_config_mgmt.yml
- import_playbook: p11_config_worker.yml
- import_playbook: p12_start_hadoop.yml