- name: Stop and start Hadoop services on management node
  hosts: management
  tasks:
  - name: Stop running namenode if exists
    ansible.builtin.shell: |
      if [ -f /tmp/hadoop-almalinux-namenode.pid ]; then
        PID=$(cat /tmp/hadoop-almalinux-namenode.pid)
        echo "Stopping namenode process $PID"
        kill -9 $PID
        sleep 3
        rm -f /tmp/hadoop-almalinux-namenode.pid
      fi
    ignore_errors: yes

  - name: Format namenode (only do once)
    ansible.builtin.shell: yes Y | hdfs namenode -format -force -nonInteractive
    args:
      creates: /opt/hadoop_tmp/hdfs/namenode/formatted

  - name: Check if formatted marker exists
    ansible.builtin.stat:
      path: /opt/hadoop_tmp/hdfs/namenode/formatted
    register: formatted_marker

  - name: Mark namenode as formatted
    ansible.builtin.shell: touch /opt/hadoop_tmp/hdfs/namenode/formatted
    when: not formatted_marker.stat.exists

  - name: Start DFS
    ansible.builtin.shell: nohup /home/almalinux/hadoop-3.4.0/sbin/start-dfs.sh &
    
  - name: Start YARN
    ansible.builtin.shell: nohup /home/almalinux/hadoop-3.4.0/sbin/start-yarn.sh &
