- name: Install required Python packages on Spark workers
  hosts: all
  become: yes
  tasks:
    - name: Ensure python3 and pip3 are installed on Debian/Ubuntu
      apt:
        name:
          - python3
          - python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure python3 and pip3 are installed on RedHat/CentOS
      yum:
        name:
          - python3
          - python3-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Upgrade pip to the latest version
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install TensorFlow, NumPy, Pandas, and PySpark without caching
      pip:
        name:
          - "tensorflow>=2.5.0"
          - numpy
          - pandas
          - "pyspark>=3.0.0"
        executable: pip3
        extra_args: "--no-cache-dir"

    - name: Remove Hadoop and Spark archives if they exist
      file:
        path: "/home/almalinux/{{ item }}"
        state: absent
      loop:
        - hadoop.tar.gz
        - spark.tgz
