---
# Playbook 20: Install and Start Node Exporter on Worker and Management Nodes
# This playbook installs Node Exporter on worker and management nodes, ensuring it is set up to run in the background for Prometheus monitoring.

- name: Notify user about Playbook 20
  hosts: localhost
  tasks:
    - name: Display playbook message
      ansible.builtin.debug:
        msg: "Running Playbook 20: Install and Start Node Exporter on Worker and Management Nodes - This playbook installs Node Exporter and ensures it runs in the background for Prometheus monitoring."

- name: Install and Start Node Exporter on Worker Nodes
  hosts: workers, management
  become: yes
  tasks:
    # Step 1: Install Go (golang)
    - name: Install Go (golang)
      # Install Go, a prerequisite for building and running Node Exporter.
      ansible.builtin.dnf:
        name: golang
        state: present

    # Step 2: Install EPEL release repository
    - name: Install EPEL release repository
      # Install the EPEL repository RPM to access Node Exporter and other additional packages.
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    # Step 3: Import the EPEL GPG key
    - name: Import EPEL GPG key
      # Import the GPG key for the EPEL repository to ensure package integrity.
      ansible.builtin.rpm_key:
        state: present
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9

    # Step 4: Install Node Exporter
    - name: Install Node Exporter from DNF
      # Install Node Exporter from the package repository.
      ansible.builtin.dnf:
        name: golang-github-prometheus-node-exporter
        state: present
        disable_gpg_check: true  # Disable GPG check for simplicity (consider enabling in production).

    # Step 5: Start Node Exporter in the background
    - name: Start Node Exporter in the background
      # Start Node Exporter as a background process using `nohup` to ensure it continues running.
      ansible.builtin.shell:
        cmd: nohup node_exporter &> /dev/null &
      args:
        executable: /bin/bash