---

# Playbook 27: Update React and backend .env files with Terraform username
# This playbook performs the following:
# 1. Retrieves the Terraform 'username' output and sets it as a temporary variable.
# 2. Creates a .env file for the React frontend with REACT_APP_USERNAME.
# 3. Creates a .env file for the backend with REACT_APP_CORS_ORIGIN.

- name: Notify user about Playbook 27
  hosts: localhost
  tasks:
    - name: Display playbook message
      ansible.builtin.debug:
        msg: "Running Playbook 27: Update React and backend .env files with Terraform username."
        
- name: Update React app .env with Terraform username
  hosts: management
  gather_facts: no
  tasks:
    - name: Retrieve Terraform username output
      delegate_to: localhost
      run_once: true
      command: terraform output -raw username
      register: terraform_username
      changed_when: false
      args:
        # Run Terraform in the correct directory (one level up from the playbook, then into 'terraform').
        chdir: "{{ playbook_dir }}/../terraform"

    - name: Debug Terraform username value
      debug:
        msg: "Terraform username is {{ terraform_username.stdout }}"

    - name: Create .env file for React app with REACT_APP_USERNAME
      copy:
        dest: "/home/almalinux/Image-Classification/frontend/my-app/.env"
        content: "REACT_APP_USERNAME={{ terraform_username.stdout }}\n"
        mode: '0644'

    - name: Create .env file for backend with REACT_APP_CORS_ORIGIN
      copy:
        dest: "/home/almalinux/Image-Classification/backend/.env"
        content: "REACT_APP_CORS_ORIGIN=https://react-{{ terraform_username.stdout }}.comp0235.condenser.arc.ucl.ac.uk\n"
        mode: '0644'
