- name: Install required Python packages on Spark workers
  hosts: all
  become: yes
  tasks:
    - name: Remove Hadoop and Spark archives if they exist
      file:
        path: "/home/almalinux/{{ item }}"
        state: absent
      loop:
        - hadoop.tar.gz
        - spark.tgz
