- name: Customise VMs for course
  hosts: all
  become: true
  become_user: root
  tasks: 
    - name: Create hosts file from template
      ansible.builtin.blockinfile:
        block: "{{ lookup('template', 'templates/hostfile.j2') }}"
        dest: /etc/hosts
        insertafter: EOF

    - name: Add hadoop tmp directory
      ansible.builtin.file:
        path: /opt/hadoop_tmp
        owner: almalinux
        group: almalinux
        state: directory

    - name: Add hdfs directory
      ansible.builtin.file:
        path: /opt/hadoop_tmp/hdfs
        owner: almalinux
        group: almalinux
        state: directory
