---
- name: Full RabbitMQ setup, configuration and firewall rules for workers[0]
  hosts: workers[0], management
  become: yes
  become_user: root
  tasks:
    - name: Create rabbitmq.repo with RabbitMQ and modern Erlang repositories
      copy:
        dest: /home/almalinux/rabbitmq.repo
        owner: root
        group: root
        mode: '0644'
        content: |
          # In /etc/yum.repos.d/rabbitmq.repo

          ##
          ## Zero dependency Erlang RPM
          ##

          [modern-erlang]
          name=modern-erlang-el9
          # Use a set of mirrors maintained by the RabbitMQ core team.
          # The mirrors have significantly higher bandwidth quotas.
          baseurl=https://yum1.rabbitmq.com/erlang/el/9/$basearch
                  https://yum2.rabbitmq.com/erlang/el/9/$basearch
          repo_gpgcheck=1
          enabled=1
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1
          type=rpm-md

          [modern-erlang-noarch]
          name=modern-erlang-el9-noarch
          # Use a set of mirrors maintained by the RabbitMQ core team.
          # The mirrors have significantly higher bandwidth quotas.
          baseurl=https://yum1.rabbitmq.com/erlang/el/9/noarch
                  https://yum2.rabbitmq.com/erlang/el/9/noarch
          repo_gpgcheck=1
          enabled=1
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
                 https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1
          type=rpm-md

          [modern-erlang-source]
          name=modern-erlang-el9-source
          # Use a set of mirrors maintained by the RabbitMQ core team.
          # The mirrors have significantly higher bandwidth quotas.
          baseurl=https://yum1.rabbitmq.com/erlang/el/9/SRPMS
                  https://yum2.rabbitmq.com/erlang/el/9/SRPMS
          repo_gpgcheck=1
          enabled=1
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
                 https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1

          ##
          ## RabbitMQ Server
          ##

          [rabbitmq-el9]
          name=rabbitmq-el9
          baseurl=https://yum2.rabbitmq.com/rabbitmq/el/9/$basearch
                  https://yum1.rabbitmq.com/rabbitmq/el/9/$basearch
          repo_gpgcheck=1
          enabled=1
          # Cloudsmith's repository key and RabbitMQ package signing key
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
                 https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1
          type=rpm-md

          [rabbitmq-el9-noarch]
          name=rabbitmq-el9-noarch
          baseurl=https://yum2.rabbitmq.com/rabbitmq/el/9/noarch
                  https://yum1.rabbitmq.com/rabbitmq/el/9/noarch
          repo_gpgcheck=1
          enabled=1
          # Cloudsmith's repository key and RabbitMQ package signing key
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
                 https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc
          gpgcheck=1
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1
          type=rpm-md

          [rabbitmq-el9-source]
          name=rabbitmq-el9-source
          baseurl=https://yum2.rabbitmq.com/rabbitmq/el/9/SRPMS
                  https://yum1.rabbitmq.com/rabbitmq/el/9/SRPMS
          repo_gpgcheck=1
          enabled=1
          gpgkey=https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
          gpgcheck=0
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
          metadata_expire=300
          pkg_gpgcheck=1
          autorefresh=1

    - name: Fire the command to copy rabbitmq.repo with sudo to /etc/yum.repos.d/rabbitmq.repo
      shell: "sudo cp /home/almalinux/rabbitmq.repo /etc/yum.repos.d/rabbitmq.repo"
      become: no

    - name: Fire the command to install socat and logrotate with sudo
      shell: "sudo dnf install socat logrotate -y"
      become: no

    - name: Fire the command to install erlang and rabbitmq-server with sudo
      shell: "sudo dnf install erlang rabbitmq-server -y"
      become: no

    - name: Fire the command to allow UFW port 5672 with sudo
      shell: "sudo ufw allow 5672"
      become: no

    - name: Fire the command to allow UFW port 5673 with sudo
      shell: "sudo ufw allow 5673"
      become: no

    - name: Fire the command to allow UFW port 15672 with sudo
      shell: "sudo ufw allow 15672"
      become: no

    - name: Fire the command to enable rabbitmq-server with sudo
      shell: "sudo systemctl enable rabbitmq-server"
      become: no

    - name: Fire the command to start rabbitmq-server with sudo
      shell: "sudo systemctl start rabbitmq-server"
      become: no

    - name: Fire the command to add RabbitMQ user with sudo
      shell: "sudo rabbitmqctl add_user myuser mypassword"
      become: no

    - name: Fire the command to set RabbitMQ user tags with sudo
      shell: "sudo rabbitmqctl set_user_tags myuser administrator"
      become: no

    - name: Fire the command to set RabbitMQ permissions for myuser with sudo
      shell: 'sudo rabbitmqctl set_permissions -p / myuser ".*" ".*" ".*"'
      become: no
